habitat_baselines:
  verbose: False
  base_task_config_path: "exp_config/base_task_config/imagenav_mp3d.yaml"
  trainer_name: "ddppo-zsvln"
  simulator_gpu_id: 0
  torch_gpu_id: 0
  video_option: []
  tensorboard_dir: "results/task1_2/tb"
  video_dir: "video_dir"
  test_episode_count: -1
  eval_ckpt_path_dir: "results/task1_2"
  num_environments: 4
  sensors: ["rgb_sensor"]
  checkpoint_folder: "results/task1_2"
  num_updates: -1
  total_num_steps: 1e9
  log_interval: 50
  log_file : "results/task1_2/train.log"
  num_checkpoints: 100
  # Force PyTorch to be single threaded as
  # this improves performance considerably
  force_torch_single_threaded: True

  rl:
    success_reward: 2.5
    slack_reward: -1e-4

    policy:
      name: "PointNavResNetPolicy"

    ppo:
      # ppo params
      clip_param: 0.2
      ppo_epoch: 2
      num_mini_batch: 2
      value_loss_coef: 0.5
      entropy_coef: 0.01
      lr: 2.5e-4
      eps: 1e-5
      max_grad_norm: 0.2
      num_steps: 64
      use_gae: True
      gamma: 0.99
      tau: 0.95
      use_linear_clip_decay: False
      use_linear_lr_decay: False
      reward_window_size: 50

      use_normalized_advantage: False

      hidden_size: 512

      # Use double buffered sampling, typically helps
      # when environment time is similar or larger than
      # policy inference time during rollout generation
      use_double_buffered_sampler: False
    ddppo:
      sync_frac: 0.6
      # The PyTorch distributed backend to use
      distrib_backend: NCCL
      # Visual encoder backbone
      pretrained_weights: data/model_data/gibson-2plus-resnet50.pth
      # Initialize with pretrained weights
      pretrained: False
      # Initialize just the visual encoder backbone with pretrained weights
      pretrained_encoder: False
      # Whether the visual encoder backbone will be trained.
      train_encoder: True
      # Whether to reset the critic linear layer
      reset_critic: True

      # Model parameters
      backbone: resnet50
      rnn_type: LSTM
      num_recurrent_layers: 2
