habitat:
  task:
    imagegoal_sensor_v2:
      type: "ImageGoalSensorV2"
      channels: "rgb"
      sampling_type: "uniform"
      bias: [0,0,0] # set position bias for goal sensor
      augmentation:
        activate: False
        hfov: [60,120]
        height: [-0.45,0.25] # from 0.8m to 1.5m
        pitch: [-5,5] # in degree
    panoramic_rgb_sensor:
      type: "PanoramicRGBSensor"
      channels: "rgb"
    goalimage_keypoint_sensor:
      type: "KeypointMatchingSensor"
      max_matched_pts: 128
      lowes_threshold: 0.5
  simulator:
    rgb_sensor: # to generate high-res visualization, use 512x512 rgb sensor
      width: 128
      height: 128